plugins {
    id 'com.android.application'
}
android {
    namespace 'com.hbe.test07'
    compileSdk 34
    defaultConfig {
        applicationId "com.hbe.test07"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
}
dependencies {
    implementation "androidx.appcompat:appcompat:1.6.1"
    implementation "androidx.core:core:1.12.0"
    implementation "com.google.code.gson:gson:2.10.1"\n    implementation "com.google.android.material:material:1.11.0"
}
